<a href="https://colab.research.google.com/github/Aryan-Deshpande/NestedML/blob/master/1PytorchBestPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pytorch numpy time

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement time (from versions: none)
ERROR: No matching distribution found for time


Use Sequential Layers When Possible

In [16]:
import torch
import torch.nn as nn

class ANN(nn.Module):
  def __init__(self):
    super(ANN,self).__init__()

    self.layers = nn.Sequential(
        nn.Linear(2,16),
        nn.ReLU(),
        nn.Linear(16,16),
        nn.ReLU(),
        nn.Linear(16,3)
    )

  def forward(self,x):
    return self.layers(x)

Don't Make Lists of Layers --> affects when tensor is on GPU, this is because List elements created are now untracked. 
Use Sequential as a work around.

In [7]:
class ANN(nn.Module):
  def __init__(self):
    super(ANN,self).__init__()

    self.midlayers =[]

    self.firstlayer = nn.Linear(30,12)

    for _ in range(230):
      self.midlayers.append(nn.Linear(12,12))
      self.midlayers.append(nn.ReLU())
    
    self.midlayers = nn.Sequential(*self.midlayers)

  def forward(self,x):
    out = self.firstlayer(x)
    out = self.midlayers(x)
    return out

Make Use of Distributions

In [24]:
model = ANN()
input_tensor = torch.rand(5,2)

print(input_tensor)
output = model(input_tensor)
print(output)

tensor([[0.0937, 0.5864],
        [0.1742, 0.2689],
        [0.1240, 0.3428],
        [0.5674, 0.4190],
        [0.7353, 0.0128]])
tensor([[-0.0806, -0.1216, -0.2025],
        [-0.0885, -0.1334, -0.2154],
        [-0.0864, -0.1308, -0.2138],
        [-0.0694, -0.1286, -0.2046],
        [-0.0774, -0.1514, -0.2228]], grad_fn=<AddmmBackward0>)


In [27]:
#Categorical Distribution 

# in this case for example 3 classes, with probability

from torch.distributions import Categorical
dist = Categorical(logits=output)
dist

# get probabilty / alt to softmax
dist.probs

tensor([[0.3515, 0.3374, 0.3111],
        [0.3525, 0.3370, 0.3105],
        [0.3525, 0.3372, 0.3103],
        [0.3551, 0.3347, 0.3102],
        [0.3580, 0.3325, 0.3095]], grad_fn=<SoftmaxBackward0>)

In [28]:
# Take Samples
dist.sample()


tensor([0, 0, 2, 1, 0])

batches = 

In [34]:
batches = [torch.rand(5,2) for _ in range(5)]
print(batches)
losses = []
for batch in batches:
# calc pred
# calc loss
  losses.append(loss.detatch()) # detatch value from gradient graph or use loss.item()
# optimization


[tensor([[0.6899, 0.4502],
        [0.2887, 0.1596],
        [0.5705, 0.3988],
        [0.1335, 0.4364],
        [0.1050, 0.7308]]), tensor([[0.9811, 0.9357],
        [0.6772, 0.8858],
        [0.6825, 0.6819],
        [0.8916, 0.6004],
        [0.9495, 0.6301]]), tensor([[0.9618, 0.9874],
        [0.2279, 0.0791],
        [0.2217, 0.4189],
        [0.5168, 0.9927],
        [0.2380, 0.6607]]), tensor([[0.9967, 0.0416],
        [0.7096, 0.9539],
        [0.0997, 0.3158],
        [0.6946, 0.5875],
        [0.7974, 0.0979]]), tensor([[0.0341, 0.2136],
        [0.8287, 0.5938],
        [0.6018, 0.0812],
        [0.8676, 0.6472],
        [0.5697, 0.7418]])]


Clean or Delete Model from GPU

In [ ]:
import gc # garbage collection
del_it = ANN()

del del_it
gc.collect()

torch.cuda.empty_cache()

ofcourse eval before testing !!!